plugins:
  issue_comment.created:
    - uses:
        - plugin: http://localhost:4000
          name: start-stop
          id: start-stop-command
          type: github
          description: "Allows a user to start/stop a bounty without negative XP impact"
          command: "/(start|stop)"
          example: "/start | /stop"
          with:
            disabledCommands: [] # Empty array means no commands are disabled
            timers:
              reviewDelayTolerance: 86000
              taskStaleTimeoutDuration: 2580000
            miscellaneous:
              maxConcurrentTasks: 3
            labels:
              time: []
              priority: []
