plugins:
  issue_comment.created:
    - uses:
      - plugin: http://localhost:4000 # or the URL where the plugin is hosted
        name: start-stop
        id: start-stop-command
        description: "Allows a user to start/stop a task without negative XP impact"
        command: "\/start|\/stop"
        example: "/start" # or "/stop"
        with:
          reviewDelayTolerance: "3 Days"
          taskStaleTimeoutDuration: "30 Days"
          maxConcurrentTasks: 3
          startRequiresWallet: true # default is true
