plugins:
  issue_comment.created:
    - uses:
        - plugin: ubiquibot/user-activity-watcher
          type: github
          with:
            unassignUserThreshold: 5
            sendRemindersThreshold: 1
