plugins:
  issues.labeled:
    - uses:
        - plugin: rndquu/user-activity-watcher:compute.yml@pull/1
          type: github
          with:
            unassignUserThreshold: 5
            sendRemindersThreshold: 1
