plugins:
  issue_comment.created:
    - uses:
        - plugin: rndquu/automated-merging:compute.yml@pull/1
          name: automated-merging
          id: automated-merging
          description: "Automatically merge pull-requests."
          with:
            approvalsRequired:
              collaborator: 1
              contributor: 1
            mergeTimeout:
              collaborator: "5 minutes"
              contributor: "5 minutes"
