plugins:
  - skipBotEvents: true
    uses:
      # hello-world-plugin
      - plugin: http://127.0.0.1:9090
        runsOn: [ "issue_comment.deleted" ]
        type: github
        with:
          response: world
