plugins:
  issues.assigned:
    - uses:
      - plugin: http://localhost:4000
        with:
          enableChecksForOrgMembers: true # Set to true to bypass checks for organization members
          minAccountAgeInDays: 365         # Minimum account age required to qualify for task assignments
          labelFilters:
            - Solidity                     # Labels used to identify protected tasks
          xpTiers:
            Junior: 10                     # Percentage threshold for qualificationm, e.g., 10% of total languages
          statThresholds:
            stars: 10                      # Minimum stars required
            prs: 5                         # Minimum PRs required
            issues: 5                      # Minimum issues required
            commits: 5                     # Minimum commits required
