plugins:
  issues.closed:
    - uses:
      - plugin: rndquu/conversation-rewards
        with:
          evmNetworkId: 100
          evmPrivateEncrypted: "wOzNgt-yKT6oFlOVz5wrBLUSYxAbKGE9Co-yvT8f9lePsx7wJwPVugS9186zdhr1T4UpkpXvq9ii5M-nWfrydMnllSkowH4LirRZsHbvRVSvDoH_uh80p6HpwqDSG3g4Nwx5q0GD3H-ne4vwXMuwWAHd"
          erc20RewardToken: "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d"
          incentives:
            requirePriceLabel: true
            contentEvaluator:
            userExtractor:
              redeemTask: true
            dataPurge:
            formattingEvaluator:
              scores:
                br: 0
                code: 1
                p: 1
                em: 0
                img: 0
                strong: 0
                blockquote: 0
                h1: 1
                h2: 1
                h3: 1
                h4: 1
                h5: 1
                h6: 1
                a: 1
                li: 1
                td: 1
                hr: 0
              multipliers:
                - select: [ ISSUE_SPECIFICATION ]
                  formattingMultiplier: 1
                  wordValue: 0.1
                - select: [ ISSUE_AUTHOR ]
                  formattingMultiplier: 1
                  wordValue: 0.2
                - select: [ ISSUE_ASSIGNEE ]
                  formattingMultiplier: 0
                  wordValue: 0
                - select: [ ISSUE_COLLABORATOR ]
                  formattingMultiplier: 1
                  wordValue: 0.1
                - select: [ ISSUE_CONTRIBUTOR ]
                  formattingMultiplier: 0.25
                  wordValue: 0.1
                - select: [ PULL_SPECIFICATION ]
                  formattingMultiplier: 0
                  wordValue: 0
                - select: [ PULL_AUTHOR ]
                  formattingMultiplier: 2
                  wordValue: 0.2
                - select: [ PULL_ASSIGNEE ]
                  formattingMultiplier: 1
                  wordValue: 0.1
                - select: [ PULL_COLLABORATOR ]
                  formattingMultiplier: 1
                  wordValue: 0.1
                - select: [ PULL_CONTRIBUTOR ]
                  formattingMultiplier: 0.25
                  wordValue: 0.1
            permitGeneration:
            githubComment:
              post: true
              debug: false
