plugins:
  issues.labeled:
    - uses:
        - plugin: rndquu/user-activity-watcher
          type: github
          with:
            unassignUserThreshold: 5
            sendRemindersThreshold: 1
