plugins:
  issue_comment.created:
    - uses:
        - plugin: http://localhost:4000
          name: command-wallet
          id: command-wallet
          description: "Helps users setting their wallet to collect subsequent task rewards."
          command: "/wallet"
          example: "/wallet ubiquibot.eth"
