plugins:
  issue_comment.created:
    - uses:
        - plugin: http://localhost:4000
          type: github
          with:
            unassignUserThreshold: 5
            sendRemindersThreshold: 1
