plugins:
  issue_comment.created:
    - uses:
        - plugin: http://localhost:4000
          name: automated-merging
          id: automated-merging
          description: "Automatically merge pull-requests."
          with:
            approvalsRequired:
              collaborator: 0
              contributor: 2
            mergeTimeout:
              collaborator: "5 minutes"
              contributor: "7 days"
