time-labels:
  - name: "Time: <1 Minute"
  - name: "Time: <5 Minutes"
  - name: "Time: <10 Minutes"
  - name: "Time: <15 Minutes"
  - name: "Time: <30 Minutes"
priority-labels:
  - name: "Priority: 1 (Normal)"
  - name: "Priority: 2 (Medium)"
  - name: "Priority: 3 (High)"
  - name: "Priority: 4 (Urgent)"
  - name: "Priority: 5 (Emergency)"
assistive-pricing: true
enable-access-control:
  label: false
  organization: false
